name: Weather AI CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Containers
        run: docker compose build

      - name: Run Containers
        run: docker compose up -d
